$(document).ready(function(){
                $("#apropos").load("../popups/apropos.html");
});
$(document).ready(function(){
                $("#credit").load("../popups/credit.html");
});
$(document).ready(function(){
                $("#aide").load("../popups/aide.html");
});
$(document).ready(function(){
                $("#mobileMenu").load("../popups/mobileMenu.html");
});
$(document).ready(function(){
                $("#transcriptionChateletDrakkar").load("../popups/retranscriptionChatelet.html");
});
